# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

jobs:
  deploy_getCurrentWeather_source:
    name: build and deploy getCurrentWeather lambda
    strategy:
      matrix:
        node-version: [14.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci --prefix ./getCurrentWeather
          npm run build --if-present --prefix ./getCurrentWeather
        env:
          CI: true
      - name: zip
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r bundle.zip ./getCurrentWeather
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: getCurrentWeather
          source: ./getCurrentWeather/index.js
          environment: PHONE_NUMBER=${{ secrets.PHONE_NUMBER }},API_KEY=${{ secrets.WEATHER_API_KEY }},BUCKET_NAME=${{ secrets.BUCKET_NAME }}
  
  deploy_sendPrecipitationReport_source:
    name: build and deploy sendPrecipitationReport lambda
    strategy:
      matrix:
        node-version: [14.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci --prefix ./sendPrecipitationReport
          npm run build --if-present --prefix ./sendPrecipitationReport
        env:
          CI: true
      - name: zip
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r bundle.zip ./sendPrecipitationReport
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: sendPrecipitationReport
          source: ./sendPrecipitationReport/index.js
          environment: PHONE_NUMBER=${{ secrets.PHONE_NUMBER }},DAYS=3,WATER_NEEDED=0.5,SEND_MESSAGE=true,BUCKET_NAME=${{ secrets.BUCKET_NAME }}
  
  deploy_appendToGoogleSheets_source:
    name: build and deploy appendToGoogleSheets lambda
    strategy:
      matrix:
        app-name: appendToGoogleSheets
        node-version: [14.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci --prefix ./${{ matrix.app-name }}
          npm run build --if-present --prefix ./${{ matrix.app-name }}
        env:
          CI: true
      - name: zip
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ${{ matrix.app-name }}Bundle.zip ./${{ matrix.app-name }}
      # This works below, however publishing on each push may not be necessary (and node modules are quite heavy)
      # - name: AWS Lambda Layer Publish
      #   uses: killdozerx2/aws-lambda-publishlayer@v1.0.0
      #   env:
      #     AWS_REGION: ${{ secrets.AWS_REGION }}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #   with:
      #     layer_name: NodeAppendToGoogleSheets
      #     zip_file: ./appendToGoogleSheetsBundle.zip
      #     description: This is a description to help me figure out if layer published as intended.
      #     compatible_runtimes: "[nodejs14.x]"
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ${{ matrix.app-name }}
          source: ./${{ matrix.app-name }}/index.js,./${{ matrix.app-name }}/google.js,./${{ matrix.app-name }}/prettyDate.js,./${{ matrix.app-name }}/aws.js # should be able to do a file list here from docs: "File list you want to zip"
          environment: GOOGLE_SHEETS_SPREADSHEET_ID=${{ secrets.GOOGLE_SHEETS_SPREADSHEET_ID }},GOOGLE_SHEETS_PRIVATE_KEY=${{ secrets.GOOGLE_SHEETS_PRIVATE_KEY }},GOOGLE_SHEETS_CLIENT_EMAIL=${{ secrets.GOOGLE_SHEETS_CLIENT_EMAIL }}
