# This is a basic workflow to help you get started with Actions

name: SendPrecipitationReport CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

jobs:
  deploy_sendPrecipitationReport_source:
    name: build and deploy sendPrecipitationReport lambda
    strategy:
      matrix:
        node-version: [14.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci --prefix ./sendPrecipitationReport
          npm run build --if-present --prefix ./sendPrecipitationReport
        env:
          CI: true
      - name: zip
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r bundle.zip ./sendPrecipitationReport
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: sendPrecipitationReport
          source: ./sendPrecipitationReport/index.js
          environment: PHONE_NUMBER=${{ secrets.PHONE_NUMBER }},DAYS=3,WATER_NEEDED=0.5,SEND_MESSAGE=true,BUCKET_NAME=${{ secrets.BUCKET_NAME }}